name: Update README Image Table

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate README
        run: python3 generate_readme.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add README.md
          git diff --staged --quiet || git commit -m "Auto update README image table"
          git push
